## Assignment_3.2

In [24]:
string = "ACADGILD"
Name = [x for x in string[0:len(string)]]
print (Name)

['A', 'C', 'A', 'D', 'G', 'I', 'L', 'D']


In [452]:
from numpy import *
string = "xyz"
Name = []
Name = [x for x in string[0:len(string)]]
#print (Name)
level_1 = []
level_2 = []
level_3 = []
matrix = [[2,3,4],[3,4,5],[4,5,6]]
matrix_1 = [5,6,7,8]

def concat_c(ch,n) : 
    temp_c = ch
    l = []
    l.append(temp_c) 
    for i in range(n) :
        temp_c = temp_c + ch
        l.append(temp_c)
    return l

def concat_l(ch, n) : 
    temp_c = ch
    l = []
    l.extend(temp_c)
    l.extend([(temp_c[i]+temp_c[i]) for i in range(n)]) 
    l.extend([(temp_c[i]+temp_c[i]) for i in range(n)])
    l.extend([(temp_c[i]+temp_c[i]+temp_c[i]+temp_c[i]) for i in range(n)])
    return l

level_1.extend([concat_c(Name[i],3) for i in range(0,len(Name))])
print(*level_1)
level_2.extend([concat_l(Name,3)])
print(*level_2)

level_3 = [[row[i]] for row in matrix for i in range(3)]
print(level_3)
matrix.append([5,6,7])
print (matrix)
shape(matrix)
matrix = insert(matrix,[3],[[5], [6], [7],[8]],axis=1)
print(matrix)

list_temp = [1,2,3]
result_5 = []
result_5.append([(list_temp[i],1) for i in range(0,len(list_temp))])
result_5.append([(list_temp[i],2) for i in range(0,len(list_temp))])
result_5.append([(list_temp[i],3) for i in range(0,len(list_temp))])
print(*result_5)
#[(1, 1), (2, 1), (3, 1), (1, 2), (2, 2), (3, 2), (1, 3), (2, 3), (3, 3)]

['x', 'xx', 'xxx', 'xxxx'] ['y', 'yy', 'yyy', 'yyyy'] ['z', 'zz', 'zzz', 'zzzz']
['x', 'y', 'z', 'xx', 'yy', 'zz', 'xx', 'yy', 'zz', 'xxxx', 'yyyy', 'zzzz']
[[2], [3], [4], [3], [4], [5], [4], [5], [6]]
[[2, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7]]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
[(1, 1), (2, 1), (3, 1)] [(1, 2), (2, 2), (3, 2)] [(1, 3), (2, 3), (3, 3)]
